# Generated by Django 5.2.7 on 2025-10-25 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(help_text='RUT del trabajador o administrador', max_length=20, unique=True)),
                ('cargo', models.CharField(help_text="Ej: 'Administrador DS49', 'Inspector Postventa', etc.", max_length=100)),
                ('correo_institucional', models.EmailField(help_text='Correo tipo nombre.apellido@techochile.cl', max_length=200, unique=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('TRAB', 'Trabajador Terreno / Postventa')], default='TRAB', help_text='Controla qué panel ve (ADMIN o TRAB)', max_length=5)),
                ('estado_conexion', models.CharField(choices=[('online', 'Conectado'), ('away', 'Ausente'), ('busy', 'En terreno'), ('offline', 'Desconectado')], default='online', help_text='Presencia estilo Discord', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Cuenta Django usada para iniciar sesión', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_trabajador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
