# Generated by Django 5.2.7 on 2025-10-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlataformaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password_plana', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('TRABAJADOR', 'Trabajador TECHO'), ('FAMILIA', 'Familia / Beneficiario')], max_length=20)),
                ('estado', models.CharField(choices=[('conectado', 'Conectado'), ('ausente', 'Ausente'), ('ocupado', 'Ocupado'), ('desconectado', 'Desconectado')], default='conectado', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Trabajador',
        ),
    ]
