# Generated by Django 5.2.7 on 2025-10-24 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutCliente', models.CharField(max_length=12, unique=True)),
                ('nombreCli', models.CharField(max_length=100)),
                ('apellidoCli', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('contrasenna', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Privilegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPrivilegio', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProyecto', models.CharField(max_length=100, unique=True)),
                ('nomProyecto', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('fechaInicio', models.DateField(blank=True, null=True)),
                ('fechaEstiTermi', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPosventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCatastro', models.CharField(choices=[('FALLA_CONSTRUCTIVA', 'Falla constructiva'), ('DAÑO_USO', 'Daño por uso'), ('OTRO', 'Otro')], max_length=200)),
                ('observacion', models.TextField()),
                ('imagen', models.TextField(blank=True, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_posventa', to='api.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folioInmueble', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=200)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='api.registroposventa')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutTrabajador', models.CharField(max_length=12, unique=True)),
                ('nombreTrab', models.CharField(max_length=100)),
                ('apellidoTrab', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('contrasenna', models.CharField(max_length=128)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('privilegio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores', to='api.privilegio')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores', to='api.proyecto')),
            ],
        ),
    ]
