# Generated by Django 5.1.13 on 2025-11-02 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfilusuario_vivienda_asignada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidencia',
            name='mime',
        ),
        migrations.RemoveField(
            model_name='evidencia',
            name='peso_bytes',
        ),
        migrations.AddField(
            model_name='evidencia',
            name='comentario',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='subido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registropostventa',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_GESTION', 'En gestión'), ('RESUELTA', 'Resuelta')], default='ABIERTA', max_length=20),
        ),
        migrations.AlterField(
            model_name='estadoinmueble',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_GESTION', 'En gestión'), ('RESUELTA', 'Resuelta')], max_length=20),
        ),
    ]
