# Generated by Django 5.1.13 on 2025-11-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_evidencia_mime_remove_evidencia_peso_bytes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='correo_personal',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
