# Generated by Django 5.2.7 on 2025-11-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_perfilusuario_apellido_perfilusuario_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichainmueble',
            options={'verbose_name': 'Ficha de Inmueble', 'verbose_name_plural': 'Fichas de Inmuebles'},
        ),
        migrations.AddField(
            model_name='fichainmueble',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega de Vivienda'),
        ),
    ]
