# Generated by Django 5.2.7 on 2025-11-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_fichainmueble_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='biografia',
            field=models.TextField(blank=True, help_text='Información adicional', verbose_name='Biografía'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=250, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='rut',
            field=models.CharField(blank=True, help_text='Formato: 12.345.678-9', max_length=12, null=True, unique=True, verbose_name='RUT'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='telefono_secundario',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono Secundario'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellido(s)'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='correo_personal',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Personal'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono Principal'),
        ),
    ]
