# Generated by Django 5.2.7 on 2025-11-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_perfilusuario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre Persona de Confianza'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='contacto_emergencia_relacion',
            field=models.CharField(blank=True, help_text='Ej: Madre, Hermano, Amigo', max_length=100, verbose_name='Relación'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='contacto_emergencia_telefono',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono Persona de Confianza'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nacionalidad',
            field=models.CharField(blank=True, default='Chilena', max_length=100, verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='cantidad_viviendas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad Total de Viviendas'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción del Proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='direccion',
            field=models.CharField(blank=True, max_length=250, verbose_name='Dirección del Proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='encargado_techo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Encargado TECHO'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('PLANIFICACION', 'Planificación'), ('EN_CONSTRUCCION', 'En Construcción'), ('ENTREGADO', 'Entregado'), ('POSTVENTA', 'En Postventa'), ('FINALIZADO', 'Finalizado')], default='PLANIFICACION', max_length=50, verbose_name='Estado del Proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_entrega_efectiva',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Entrega Efectiva'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='telefono_encargado',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono Encargado'),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='block_villa',
            field=models.CharField(blank=True, help_text='Opcional', max_length=50, verbose_name='Block/Villa'),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='direccion',
            field=models.CharField(blank=True, help_text='Calle y número', max_length=250, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número de Casa/Depto'),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='rut_propietario',
            field=models.CharField(blank=True, help_text='RUT de la familia beneficiaria', max_length=12, verbose_name='RUT Propietario/Beneficiario'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_estimada_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Término'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre del Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='cant_banos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Baños'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='cant_cuartos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Cuartos'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='piso',
            field=models.CharField(blank=True, max_length=50, verbose_name='Piso'),
        ),
    ]
