# Generated by Django 5.2.7 on 2025-11-16 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_perfilusuario_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vivienda',
            options={'ordering': ['proyecto__codigo', 'numero'], 'verbose_name': 'Vivienda', 'verbose_name_plural': 'Viviendas'},
        ),
        migrations.AddField(
            model_name='vivienda',
            name='constructora',
            field=models.ForeignKey(blank=True, help_text='Constructora asignada a esta vivienda', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.constructora', verbose_name='Constructora'),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='email_propietario',
            field=models.EmailField(blank=True, help_text='Correo electrónico del beneficiario', max_length=254, verbose_name='Email Propietario'),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='nombre_propietario',
            field=models.CharField(blank=True, help_text='Nombre y apellidos del beneficiario', max_length=200, verbose_name='Nombre Completo Propietario'),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='telefono_propietario',
            field=models.CharField(blank=True, help_text='Teléfono del propietario', max_length=20, verbose_name='Teléfono de Contacto'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='direccion',
            field=models.CharField(blank=True, help_text='Calle principal', max_length=250, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viviendas', to='core.proyecto'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='rut_propietario',
            field=models.CharField(blank=True, help_text='RUT de la familia beneficiaria (ej: 12.345.678-9)', max_length=12, verbose_name='RUT Propietario'),
        ),
    ]
