# Generated by Django 5.2.7 on 2025-11-25 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_vivienda_options_vivienda_constructora_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registropostventa',
            name='comentario_cierre',
            field=models.TextField(blank=True, verbose_name='Comentario de Cierre'),
        ),
        migrations.AddField(
            model_name='registropostventa',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registropostventa',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_REVISION', 'En revisión'), ('EN_GESTION', 'En gestión'), ('RESUELTA', 'Resuelta'), ('CERRADO', 'Cerrado')], default='ABIERTA', max_length=20),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='comentarios/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.registropostventa')),
            ],
        ),
    ]
