# Generated by Django 5.2.7 on 2025-11-26 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_registropostventa_comentario_cierre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registropostventa',
            name='comentario_cierre',
        ),
        migrations.RemoveField(
            model_name='registropostventa',
            name='fecha_cierre',
        ),
        migrations.AlterField(
            model_name='registropostventa',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_GESTION', 'En gestión'), ('RESUELTA', 'Resuelta')], default='ABIERTA', max_length=20),
        ),
        migrations.CreateModel(
            name='RegistroComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.registropostventa')),
            ],
            options={
                'ordering': ('-creado_en',),
            },
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
