# Generated by Django 5.2.7 on 2025-11-26 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_registropostventa_comentario_cierre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NUEVA_OBSERVACION', 'Nueva Observación'), ('OBSERVACION_RESUELTA', 'Observación Resuelta'), ('OBSERVACION_ACTUALIZADA', 'Observación Actualizada'), ('PROYECTO_ACTUALIZADO', 'Proyecto Actualizado'), ('COMENTARIO_AGREGADO', 'Comentario Agregado'), ('DS49_VENCIMIENTO', 'DS49 Próximo a Vencer'), ('SISTEMA', 'Notificación del Sistema')], max_length=50, verbose_name='Tipo de Notificación')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('url_destino', models.CharField(help_text='URL a donde redirigir al hacer click', max_length=500, verbose_name='URL de Destino')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creada_en'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='core_notifi_usuario_c30a38_idx'), models.Index(fields=['-creada_en'], name='core_notifi_creada__51250f_idx')],
            },
        ),
    ]
