# Generated by Django 5.2.7 on 2025-11-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropostventa',
            name='estado_seguimiento',
            field=models.CharField(choices=[('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado')], default='EN_REVISION', max_length=20, verbose_name='Estado de Seguimiento'),
        ),
        migrations.AddField(
            model_name='registropostventa',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='registropostventa',
            name='urgencia',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=20),
        ),
    ]
